// <auto-generated />
using System;
using IF.Tools.Templates.Editor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IF.Tools.Templates.Editor.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190806114001_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("IF.Tools.Templates.Editor.IFDll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IFDllId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IFDllId");

                    b.ToTable("Dlls");
                });

            modelBuilder.Entity("IF.Tools.Templates.Editor.IFProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IFProjectTemplateId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IFProjectTemplateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("IF.Tools.Templates.Editor.IFProjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("IF.Tools.Templates.Editor.IFDll", b =>
                {
                    b.HasOne("IF.Tools.Templates.Editor.IFDll")
                        .WithMany("Dependencies")
                        .HasForeignKey("IFDllId");
                });

            modelBuilder.Entity("IF.Tools.Templates.Editor.IFProject", b =>
                {
                    b.HasOne("IF.Tools.Templates.Editor.IFProjectTemplate", "ProjectTemplate")
                        .WithMany("ProjectList")
                        .HasForeignKey("IFProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
